[package]
name = "gart"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"

[dev-dependencies]
insta = { version = "1.46.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
